cse_website/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('curriculum/', include('curriculum.urls')),
    path('people/', include('people.urls')),
    path('announcement/', include('announcement.urls')),
    path('research/', include('research.urls')),
    path('admission/', include('admission.urls')),

    path('ckeditor', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('account/', views.account_redirect, name='account-redirect'),
    path('contact/', views.contact, name='contact'),
    path('developer/', views.developer, name='developer'),
    path('about/', views.about, name='about'),
    path('undergrad-major/', views.undergrad_major, name='umajor'),
    path('undergrad-second-major/', views.undergrad_second_major, name='usecmajor'),
    path('masters/', views.masters, name='masters'),
    path('phd/', views.phd, name='phd'),
    path('ccna/', views.ccna, name='ccna'),
]

people/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('faculty/', views.faculty, name='faculty'),
    path('faculty/<int:user_id>', views.faculty_detail, name='faculty_detail'),
    path('faculty/publications/<int:user_id>', views.faculty_publications, name='faculty_publications'),
    path('faculty/update-publications/<int:faculty_id>', views.update_publications, name='update_publications'),
    path('faculty/edit', views.update_faculty, name='update_faculty'),


    path('faculty/add_education', views.add_education, name='add_education'),
    path('faculty/edit_education\<int:education_id>', views.edit_education, name='edit_education'),
    path('faculty/delete_education/<int:education_id>', views.delete_education, name='delete_education'),

    path('faculty/add_experience', views.add_experience, name='add_experience'),
    path('faculty/edit_experience\<int:experience_id>', views.edit_experience, name='edit_experience'),
    path('faculty/delete_experience/<int:experience_id>', views.delete_experience, name='delete_experience'),

    path('faculty/add_publication', views.add_publication, name='add_publication'),
    path('faculty/edit_publication/<int:publication_id>', views.edit_publication, name='edit_publication'),
    path('faculty/delete_publication/<int:publication_id>', views.delete_publication, name='delete_publication'),

    path('faculty/add_social_profile', views.add_social_profile, name='add_social_profile'),
    #path('faculty/delete_social_profile/<int:social_profile_id>', views.delete_social_profile, name='delete_social_profile'),

    path('faculty/awards/<int:user_id>', views.faculty_awards, name='faculty_awards'),
    path('faculty/add_award', views.add_award, name='add_award'),
    path('faculty/edit_award\<int:award_id>', views.edit_award, name='edit_award'),
    path('faculty/delete_award/<int:award_id>', views.delete_award, name='delete_award'),

    path('student/', views.student, name='student'),
    path('staff/', views.staff, name='staff'),
]

people/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from bs4 import  BeautifulSoup as bsoup
from urllib.request import urlopen as urlReq


class ResearchArea(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Batch(models.Model):
    batch_year = models.IntegerField()
    syllabus = models.FileField(blank=True, null=True, upload_to='syllabus/')

    def __str__(self):
        return str(self.batch_year)

    class Meta:
        verbose_name_plural = "batches"


class User(AbstractUser):
    email = models.EmailField(unique=True)
    is_faculty = models.BooleanField(default=False)
    username = models.CharField(blank=True, null=True, max_length=150, default="N")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'is_faculty']

    def __str__(self):
        return self.email


class Faculty(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    name = models.CharField(max_length=200)
    about = models.CharField(blank=True, null=True, max_length=2000, default='Hi. A am a proud faculty of SUST CSE.')
    designation = models.CharField(max_length=200)
    image = models.ImageField(blank=True, null=True, upload_to='people/images/')
    office = models.CharField(max_length=200)
    contact = models.CharField(max_length=200, blank=True, null=True)
    research_interest = models.ManyToManyField(ResearchArea, related_name="faculty")

    STATUS = (
        ('in_service', 'In service'),
        ('on_leave', 'On leave'),
        ('ex', 'Ex Faculty'),
    )

    status = models.CharField(max_length=20, choices=STATUS)
    personal_website = models.URLField(blank=True, null=True)
    google_scholars_link = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.name

    def getFacultyStatus(self):
        if self.status == 'in_service':
            return "In service"
        elif self.status == 'on_leave':
            return "On leave"
        elif self.status == 'ex':
            return "Ex Faculty"




    class Meta:
        verbose_name_plural = "faculties"


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    name = models.CharField(max_length=200)
    registration_no = models.CharField(max_length=12)
    STATUS = (
        ('current', 'Current'),
        ('allumni', 'Allumni'),
    )
    status = models.CharField(max_length=20, choices=STATUS)
    session = models.CharField(max_length=10)
    batch = models.ForeignKey(Batch, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class SocialProfile(models.Model):
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    link = models.URLField()

    def __str__(self):
        return self.link


class ResearchStudent(models.Model):
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    research_area = models.ForeignKey(ResearchArea, on_delete=models.CASCADE)

    def __str__(self):
        return self.faculty.name + " -> " + self.student.name


class Award(models.Model):
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    details = models.TextField()
    image = models.ImageField(blank=True, null=True, upload_to='awards/images/')

    def __str__(self):
        return self.title


class Experience(models.Model):
    EXP_TYPE = (
        ('academic', 'Academic'),
        ('technical', 'Technical'),
    )
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    experience_type = models.CharField(max_length=20, choices=EXP_TYPE)
    organization = models.CharField(max_length=200)
    designation = models.CharField(max_length=200)
    time_duration = models.CharField(max_length=100)
    order_number = models.IntegerField(default=1)

    def __str__(self):
        return self.get_experience_type_display()

    class Meta:
        ordering = ['order_number']


class Education(models.Model):
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    degree = models.CharField(max_length=100)
    institution = models.CharField(max_length=200)
    passing_year = models.IntegerField()
    specialization = models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return self.degree

    class Meta:
        ordering = ['-passing_year']


class Staff(models.Model):
    name = models.CharField(max_length=200)
    designation = models.CharField(max_length=200)
    image = models.ImageField(blank=True, null=True, upload_to='people/images/')
    office = models.CharField(max_length=200)
    contact = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    STATUS = (
        ('in_service', 'In service'),
        ('ex', 'Ex Staff'),
    )
    status = models.CharField(max_length=20, choices=STATUS)

    def __str__(self):
        return self.name

    def getStaffStatus(self):
        if self.status == 'in_service':
            return "In service"
        elif self.status == 'ex':
            return "Ex Staff"

people/forms.py
from django import forms
from .models import *
from research.models import Publication, PublicationType


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'


class FacultyForm(forms.ModelForm):
    class Meta:
        model = Faculty
        exclude = ('user',)


class ExperienceForm(forms.ModelForm):
    class Meta:
        model = Experience
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', '')
        super(ExperienceForm, self).__init__(*args, **kwargs)
        self.fields['faculty'] = forms.ModelChoiceField(queryset=Faculty.objects.filter(user=user), initial=0)


class ExperienceEditForm(forms.ModelForm):
    class Meta:
        model = Experience
        fields = '__all__'


class EducationForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', '')
        super(EducationForm, self).__init__(*args, **kwargs)
        self.fields['faculty'] = forms.ModelChoiceField(queryset=Faculty.objects.filter(user=user), initial=0)


class EducationEditForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = '__all__'


class PublicationForm(forms.ModelForm):
    class Meta:
        model = Publication
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', '')
        super(PublicationForm, self).__init__(*args, **kwargs)
        self.fields['author_faculty'] = forms.ModelChoiceField(queryset=Faculty.objects.filter(user=user), initial=0)
        self.fields['author_student'] = forms.ModelMultipleChoiceField(queryset=Student.objects.all())
        self.fields['publication_type'] = forms.ModelChoiceField(queryset=PublicationType.objects.all())


class PublicationEditForm(forms.ModelForm):
    class Meta:
        model = Publication
        fields = '__all__'


class ResearchInterestForm(forms.ModelForm):
    class Meta:
        model = Publication
        fields = '__all__'


class SocialProfileForm(forms.ModelForm):
    class Meta:
        model = SocialProfile
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', '')
        super(SocialProfileForm, self).__init__(*args, **kwargs)
        self.fields['faculty'] = forms.ModelChoiceField(queryset=Faculty.objects.filter(user=user), initial=0)


class AwardForm(forms.ModelForm):
    class Meta:
        model = Award
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', '')
        super(AwardForm, self).__init__(*args, **kwargs)
        self.fields['faculty'] = forms.ModelChoiceField(queryset=Faculty.objects.filter(user=user), initial=0)


class AwardEditForm(forms.ModelForm):
    class Meta:
        model = Award
        fields = '__all__'

templates/people/faculty-add-award.html
{% extends 'base.html' %}
{% block title %}Award{% endblock %}
{% block content %}


    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>
    <style>
        input[type="text"], input[type="email"], input[type="number"], input[type="url"], textarea, select {
            width: 100%;
            height: auto;
            font-family: "Roboto", sans-serif;
            outline: 0;
            background: #d7d7d7;
            color: black;
            border: 0;
            margin: 8px 16px 15px;
            padding: 15px;
            box-sizing: border-box;
            font-size: 14px;
        }

        input[type="file"]{
            margin-bottom: 25px;
        }

        input[type=number]::-webkit-inner-spin-button,
        input[type=number]::-webkit-outer-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        table {
            width: 85%;
        }

    </style>
    {% if user.is_authenticated %}
    <div class="content-admission-form">
        <div class="admission-form-content-overlay">
            <div class="admission-form-content">
                <div class="admission-form-container-card-header">
                    Add Award Info
                </div>

                <div class="admission-form-container-card">
                    <form class="form-horizontal" method="POST" action="">
                    {% csrf_token %}
                    <table>
                        {% for field in award_form %}
                            <tr>
                                <th>{{ field.label_tag }}</th>
                                <td>
                                    {{ field.errors }}
                                    {{ field }}
                                    {{ field.help_text }}
                                </td>
                            </tr>
                        {% endfor %}


                    </table>
                    <div class="row spacer input-group-append">
                        <button type="submit" class="submit-button">Submit</button>
                    </div>
                </form>
                </div>
            <br>
            </div>
        </div>
    </div>
{% else %}
    <p>You have nothing to do here</p>
{% endif %}

{% endblock %}

templates/people/faculty-add-education.html
{% extends 'base.html' %}
{% block title %}Education{% endblock %}
{% block content %}


    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>
    <style>
        input[type="text"], input[type="email"], input[type="number"], input[type="url"], textarea, select {
            width: 100%;
            height: auto;
            font-family: "Roboto", sans-serif;
            outline: 0;
            background: #d7d7d7;
            color: black;
            border: 0;
            margin: 8px 16px 15px;
            padding: 15px;
            box-sizing: border-box;
            font-size: 14px;
        }

        input[type="file"] {
            margin-bottom: 25px;
        }

        input[type=number]::-webkit-inner-spin-button,
        input[type=number]::-webkit-outer-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        table {
            width: 85%;
        }

    </style>
    {% if user.is_authenticated %}
        <div class="content-admission-form">
            <div class="admission-form-content-overlay">
                <div class="admission-form-content">
                    <div class="admission-form-container-card-header">
                        Add Education to Profile
                    </div>

                    <div class="admission-form-container-card">
                        <form class="form-horizontal" method="POST" action="">
                            {% csrf_token %}
                            <table>
                                {% for field in education_form %}
                                    <tr>
                                        <th>{{ field.label_tag }}</th>
                                        <td>
                                            {{ field.errors }}
                                            {{ field }}
                                            {{ field.help_text }}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                            <div class="row spacer input-group-append">
                                <button type="submit" class="submit-button">Submit</button>
                            </div>
                        </form>
                        <br>

                        <a href="{% url 'faculty_detail' user.id %}">Back to Profile Page</a>

                    </div>
                    <br>
                </div>
            </div>
        </div>
    {% else %}
        <p>You have nothing to do here</p>
    {% endif %}

{% endblock %}

templates/people/faculty-add-experience.html
{% extends 'base.html' %}
{% block title %}Add Experience{% endblock %}
{% block content %}

    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>
    <style>
        input[type="text"], input[type="email"], input[type="number"], input[type="url"], textarea, select {
            width: 100%;
            height: auto;
            font-family: "Roboto", sans-serif;
            outline: 0;
            background: #d7d7d7;
            color: black;
            border: 0;
            margin: 8px 16px 15px;
            padding: 15px;
            box-sizing: border-box;
            font-size: 14px;
        }

        input[type="file"] {
            margin-bottom: 25px;
        }

        input[type=number]::-webkit-inner-spin-button,
        input[type=number]::-webkit-outer-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        table {
            width: 85%;
        }

    </style>
    {% if user.is_authenticated %}
        <div class="content-admission-form">
            <div class="admission-form-content-overlay">
                <div class="admission-form-content">
                    <div class="admission-form-container-card-header">
                        Add Work Experience to Profile
                    </div>

                    <div class="admission-form-container-card">
                        <form class="form-horizontal" method="POST" action="">
                            {% csrf_token %}
                            <table>
                                {% for field in experience_form %}
                                    <tr>
                                        <th>{{ field.label_tag }}</th>
                                        <td>
                                            {{ field.errors }}
                                            {{ field }}
                                            {{ field.help_text }}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                            <div class="row spacer input-group-append">
                                <button type="submit" class="submit-button">Submit</button>
                            </div>
                        </form>
                        <br>

                        <a href="{% url 'faculty_detail' user.id %}">Back to Profile Page</a>

                    </div>
                    <br>
                </div>
            </div>
        </div>
    {% else %}
        <p>You have nothing to do here</p>
    {% endif %}
{% endblock %}

templates/people/faculty-add-publication.html
{% extends 'base.html' %}
{% block title %}Add Publication{% endblock %}
{% block content %}

{% if user.is_authenticated %}


     <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>
    <style>
        input[type="text"], input[type="email"], input[type="number"], input[type="url"], textarea, select {
            width: 100%;
            height: auto;
            font-family: "Roboto", sans-serif;
            outline: 0;
            background: #d7d7d7;
            color: black;
            border: 0;
            margin: 8px 16px 15px;
            padding: 15px;
            box-sizing: border-box;
            font-size: 14px;
        }

        input[type="file"] {
            margin-bottom: 25px;
        }

        input[type=number]::-webkit-inner-spin-button,
        input[type=number]::-webkit-outer-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        table {
            width: 85%;
        }

    </style>
    {% if user.is_authenticated %}
        <div class="content-admission-form">
            <div class="admission-form-content-overlay">
                <div class="admission-form-content">
                    <div class="admission-form-container-card-header">
                        Add Publication to Profile
                    </div>

                    <div class="admission-form-container-card">
                        <form class="form-horizontal" method="POST" action="">
                            {% csrf_token %}
                            <table>
                                {% for field in publication_form %}
                                    <tr>
                                        <th>{{ field.label_tag }}</th>
                                        <td>
                                            {{ field.errors }}
                                            {{ field }}
                                            {{ field.help_text }}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                            <div class="row spacer input-group-append">
                                <button type="submit" class="submit-button">Submit</button>
                            </div>
                        </form>
                        <br>

                        <a href="{% url 'faculty_detail' user.id %}">Back to Profile Page</a>

                    </div>
                    <br>
                </div>
            </div>
        </div>
    {% else %}
        <p>You have nothing to do here</p>
    {% endif %}


{% else %}
    <p>You have nothing to do here</p>
{% endif %}
{% endblock %}

templates/people/faculty-add-social-profile.html
{% extends 'base.html' %}
{% block title %}Social Profile{% endblock %}
{% block content %}

    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>
    <style>
        input[type="text"], input[type="email"], input[type="number"], input[type="url"], textarea, select {
            width: 100%;
            height: auto;
            font-family: "Roboto", sans-serif;
            outline: 0;
            background: #d7d7d7;
            color: black;
            border: 0;
            margin: 8px 16px 15px;
            padding: 15px;
            box-sizing: border-box;
            font-size: 14px;
        }

        input[type="file"] {
            margin-bottom: 25px;
        }

        input[type=number]::-webkit-inner-spin-button,
        input[type=number]::-webkit-outer-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        table {
            width: 85%;
        }

    </style>
    {% if user.is_authenticated %}
        <div class="content-admission-form">
            <div class="admission-form-content-overlay">
                <div class="admission-form-content">
                    <div class="admission-form-container-card-header">
                        Add Social Profile
                    </div>

                    <div class="admission-form-container-card">
                        <form class="form-horizontal" method="POST" action="">
                            {% csrf_token %}
                            <table>
                                {% for field in social_profile_form %}
                                    <tr>
                                        <th>{{ field.label_tag }}</th>
                                        <td>
                                            {{ field.errors }}
                                            {{ field }}
                                            {{ field.help_text }}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                            <div class="row spacer input-group-append">
                                <button type="submit" class="submit-button">Submit</button>
                            </div>
                        </form>
                        <br>

                        <a href="{% url 'faculty_detail' user.id %}">Back to Profile Page</a>

                    </div>
                    <br>
                </div>
            </div>
        </div>
    {% else %}
        <p>You have nothing to do here</p>
    {% endif %}


{% endblock %}

templates/people/faculty-award.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Award{% endblock %}
{% block content %}


    <div class="curriculum-background">
        <div class="program-content-overlay">
            <div class="program-content">
                <div class="">
                    <div class="row">
                        <div class="container">
                            <div class="col-md-12">
                                <h2 class="detail-card-header honor-detail-card-header">
                                    <i class="material-icons">school</i>Awards Of {{ faculty.name }}
                                    {% if user.is_authenticated %}
                                        {% if user.id == faculty.user.id %}
                                            <a href="{% url 'add_award' %}"><i class="material-icons add-button" >add_circle_outline</i></a>
                                        {% endif %}
                                    {% endif %}

                                </h2>
                                <div class="classes class-single detail-card news-detail-card">
                                    <div class="desc desc2 row">
                                        <div class="col-md-12 program-detail-container">

                                            {% if faculty.award_set.all %}
                                                {% for award in faculty.award_set.all %}
                                                    <div class="card">
                                                        <div class="desc">
                                                            <div class="col-md-12 animate-box">

                                                                <div class="pull-left" style="margin-right: 25px;">

                                                                    {% if not award.image %}
                                                                        <img height="250px;" width="300px;"
                                                                        src="{% static 'images/no_image_available.jpeg' %}">
                                                                    {% else %}
                                                                        <img height="250px;" width="300px;"
                                                                         src="/media/{{ award.image }}">
                                                                    {% endif %}
                                                                </div>

                                                                <div class="honor-detail-desc">
                                                                    <h2 style="display: inline-block;">{{ award.title }}</h2>
                                                                    {% if user.is_authenticated %}
                                                                        {% if user.id == faculty.user.id %}
                                                                            <a href="{% url 'delete_award' award.id %}"><i
                                                                                    class="material-icons"
                                                                                    style="display: inline-block; float:right;">clear</i></a>
                                                                            <a href="{% url 'edit_award' award.id %}"><i
                                                                                        class="material-icons"
                                                                                        style="display: inline-block; float:right;">edit</i></a>
                                                                        {% endif %}
                                                                    {% endif %}
                                                                    <p>
                                                                        {{ award.details }}
                                                                    </p>
                                                                </div>

                                                            </div>
                                                        </div>
                                                    </div>
                                                {% endfor %}
                                            {% else %}
                                                <center>
                                                    <img class="img img-responsive" width="25%" height="auto"
                                                         src="{% static 'images/backgrounds/nothing_found.svg' %}">
                                                    <br>
                                                    <h4 style="color: darkred">Sorry! No Award Records found.</h4>
                                                </center>
                                            {% endif %}

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/people/test2.html
{{faculty.name}}