admission/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('second-major/', views.admission_second_major, name='admission_second_major'),

    path('download-form/<path:path>', views.download_form, name='download_form'),

    path('phd/', views.admission_phd, name='admission_phd'),

    path('masters/', views.admission_masters, name='admission_masters'),

    path('ccna/', views.admission_ccna, name='admission_ccna'),

]

cse_website/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('curriculum/', include('curriculum.urls')),
    path('people/', include('people.urls')),
    path('announcement/', include('announcement.urls')),
    path('research/', include('research.urls')),
    path('admission/', include('admission.urls')),

    path('ckeditor', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('account/', views.account_redirect, name='account-redirect'),
    path('contact/', views.contact, name='contact'),
    path('developer/', views.developer, name='developer'),
    path('about/', views.about, name='about'),
    path('undergrad-major/', views.undergrad_major, name='umajor'),
    path('undergrad-second-major/', views.undergrad_second_major, name='usecmajor'),
    path('masters/', views.masters, name='masters'),
    path('phd/', views.phd, name='phd'),
    path('ccna/', views.ccna, name='ccna'),
]

admission/models.py
from django.db import models


class SecondMajorApplication(models.Model):
    registration_no = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=200)
    department = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()
    address = models.CharField(max_length=1000)
    reason_of_study = models.TextField()

    def __str__(self):
        return self.registration_no


class SecondMajorCourse(models.Model):
    registration = models.ForeignKey(SecondMajorApplication, on_delete=models.CASCADE)
    course_code = models.CharField(max_length=6)
    course_credit = models.FloatField()
    course_grade = models.CharField(max_length=2, default="F")

    def __str__(self):
        return self.course_code

announcement/models.py
from django.db import models
from curriculum.models import Program, Semester
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class Notice(models.Model):
    program_name = models.ForeignKey(Program, on_delete=models.CASCADE)
    year_semester = models.ForeignKey(Semester, blank=True, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=500)
    details = models.TextField(blank=True, null=True)
    date_published = models.DateField(auto_now_add=True)
    upload = models.FileField(blank=True, null=True, upload_to='notices/%Y/%m/%d/')

    def __str__(self):
        return self.title


class HonorBoard(models.Model):
    title = models.CharField(max_length=500)
    image = models.ImageField(blank=True, null=True, upload_to='images/')
    details = models.TextField()

    def __str__(self):
        return self.title


class News(models.Model):
    title = models.CharField(max_length=500)
    date_published = models.DateField(auto_now_add=True)
    details = models.TextField()
    image = models.ImageField(blank=True, null=True, upload_to='images/')

    def __str__(self):
        return self.title

    def getStrippedName(self):
        return self.title.replace(" ", "")

    def getNewsIntro(self):
        newsDetail = self.details
        if len(newsDetail) > 300:
            return newsDetail[0:300]
        else:
            return newsDetail

    class Meta:
        verbose_name_plural = "news"


class Event(models.Model):
    title = models.CharField(max_length=500)
    event_date = models.DateTimeField()
    location = models.CharField(max_length=500)
    details = models.TextField()
    image = models.ImageField(blank=True, null=True, upload_to='images/')

    def __str__(self):
        return self.title

    def getStrippedName(self):
        return self.title.replace(" ", "")

    def getEventsIntro(self):
        eventDetail = self.details
        if len(eventDetail) > 300:
            return eventDetail[0:300]
        else:
            return eventDetail

admission/forms.py
from django import forms
from django.forms import modelformset_factory
from .models import *


class SecondMajorApplicationForm(forms.ModelForm):
    class Meta:
        model = SecondMajorApplication
        fields = '__all__'


SecondMajorCourseFormset = modelformset_factory(
    SecondMajorCourse,
    fields=('course_code', 'course_credit', 'course_grade', ),
    extra=1,
)

admission/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse, Http404
from .models import *
from .forms import *
from curriculum.models import Program
import os
from django.conf import settings


def admission_second_major(request):
    program = Program.objects.get(program_name="undergraduate_second_major")
    context = {'program': program}
    return render(request, 'admission/program-admission.html', context)


def admission_phd(request):
    program = Program.objects.get(program_name="phd")
    context = {'program': program}
    return render(request, 'admission/program-admission.html', context)


def admission_masters(request):
    program = Program.objects.get(program_name="masters")
    context = {'program': program}
    return render(request, 'admission/program-admission.html', context)


def admission_ccna(request):
    program = Program.objects.get(program_name="ccna")
    context = {'program': program}
    return render(request, 'admission/program-admission.html', context)

'''
def second_major_application(request):
    if request.method == 'GET':
        application_form = SecondMajorApplicationForm(request.GET or None)

    elif request.method == 'POST':
        application_form = SecondMajorApplicationForm(request.POST)

        if application_form.is_valid():
            application = application_form.save()
            return redirect('admission_second_major')

    return render(request, 'admission/second-major-application-form.html', {
        'application_form': application_form,
    })



def second_major_application(request):

    if request.method == 'GET':
        application_form = SecondMajorApplicationForm(request.GET or None)
        formset = SecondMajorCourseFormset(queryset=SecondMajorCourse.objects.none())

    elif request.method == 'POST':
        application_form = SecondMajorApplicationForm(request.POST)
        formset = SecondMajorCourseFormset(request.POST)

        if application_form.is_valid() and formset.is_valid():
            application = application_form.save()

            for form in formset:
                course = form.save(commit=False)
                course.registration = application
                course.save()
            return redirect('admission_second_major')

    context = {
        'application_form': application_form,
        'formset': formset,
    }
    return render(request, 'admission/second-major-application-form.html', context)
'''

def download_form(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)

    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/pdf")
            response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)
            return response
    raise Http404

templates/admission/program-admission.html
{% extends 'base.html' %}
{% block title %}Admission{% endblock %}
{% block content %}

<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
<!--<div class="people-detail-header-image">
    <span class="people-detail-header-overlay"></span>
</div>-->
<div class="program-background">
    <div class="program-content-overlay">
        <div class="program-content">
            <div class="">
                <div class="row">
                    <div class="container">
                        <div class="col-md-12">
                            <h2 class="program-detail-card-header" >
                                <i class="material-icons">school</i>
                                Program - {{ program.get_program_name_display }}</h2>
                            <div class="classes class-single program-detail-header-card">
                                <div class="desc desc2 row">
                                    <div class="col-md-12 program-detail-container">
                                        <center class="faculty_detail_description">
                                            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
                                            tempor
                                            incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                                            nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                            consequat.
                                            Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore
                                            eu fugiat nulla pariatur. Excepteur sint Lorem ipsum dolor sit amet,
                                            consectetur
                                            adipiscing elit, sed do eiusmod tempor
                                            incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                                            nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                            consequat.
                                            Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore
                                            eu fugiat nulla pariatur. Excepteur sint Lorem ipsum dolor sit amet,
                                            consectetur
                                            adipiscing elit, sed do eiusmod tempor
                                            incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                                            nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                            consequat.
                                            Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore
                                            eu fugiat nulla pariatur. Excepteur sint

                                        </center>
                                        <center>
                                            <a href="#program-detail" style="color: black"><i class="material-icons">keyboard_arrow_down</i></a>
                                        </center>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div id="program-detail">
                <div class="row">
                    <div class="container">
                        <div class="col-md-12">
                            <h2 class="program-detail-card-header" >
                                <i class="material-icons">school</i>
                                {{ program.get_program_name_display }} - Program Detail</h2>
                            <div class="classes class-single program-detail-container-card">
                                <div class="desc desc2 row">
                                    <div class="col-md-12 program-detail-container">
                                        <center class="faculty_detail_description">
                                            {{ program.details|safe }}
                                        </center>

                                    </div>
                                    <div class="col-md-12 program-detail-container">
                                        <center class="faculty_detail_description">
                                            {% if program.admission_form %}
                                                Wanna Get Admitted to {{ program.get_program_name_display }} fill up this
                                            <a href="{% url 'download_form' program.admission_form.name %}">form</a>
                                            {% endif %}
                                        </center>
                                        </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br><br>
        </div>
    </div>
</div>
{% endblock %}

templates/admission/second-major-application-form-course.html
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<form class="form-horizontal" method="POST" action="" style="text-align:center;">
    {% csrf_token %}

{{ formset.management_form }}
{% for form in formset %}
<div class="form-row">
    {{form.as_p}}
    <button class="btn btn-success add-form-row"><i class="material-icons">add_circle_outline</i></button>

</div>
{% endfor %}
<br><br>
    <button type="submit" class="btn btn-block btn-primary">Submit</button>
</form>

</body>

<script type='text/javascript'>
function updateElementIndex(el, prefix, ndx) {
    var id_regex = new RegExp('(' + prefix + '-\\d+)');
    var replacement = prefix + '-' + ndx;
    if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
    if (el.id) el.id = el.id.replace(id_regex, replacement);
    if (el.name) el.name = el.name.replace(id_regex, replacement);
}
function cloneMore(selector, prefix) {
    var newElement = $(selector).clone(true);
    var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
    newElement.find(':input').each(function() {
        var name = '';
        var id = 'id_' + name;
        $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
    });
    total++;
    $('#id_' + prefix + '-TOTAL_FORMS').val(total);
    $(selector).after(newElement);
    var conditionRow = $('.form-row:not(:last)');
    conditionRow.find('.btn.add-form-row')
    .removeClass('btn-success').addClass('btn-danger')
    .removeClass('add-form-row').addClass('remove-form-row')
    .html('<i class="material-icons">remove_circle_outline</i>');
    return false;
}
function deleteForm(prefix, btn) {
    var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
    if (total > 1){
        btn.closest('.form-row').remove();
        var forms = $('.form-row');
        $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
        for (var i=0, formCount=forms.length; i<formCount; i++) {
            $(forms.get(i)).find(':input').each(function() {
                updateElementIndex(this, prefix, i);
            });
        }
    }
    return false;
}
$(document).on('click', '.add-form-row', function(e){
    console.log("hello");
    e.preventDefault();
    cloneMore('.form-row:last', 'form');
    return false;
});
$(document).on('click', '.remove-form-row', function(e){
    e.preventDefault();
    deleteForm('form', $(this));
    return false;
});
</script>

templates/admission/second-major-application-form.html
{% extends 'base.html' %}
{% block title %}Apply for Admission{% endblock %}
{% block content %}
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>
    <style>
        input[type="text"], input[type="email"], input[type="number"], textarea {
            width: 100%;
            height: auto;
            font-family: "Roboto", sans-serif;
            outline: 0;
            background: #d7d7d7;
            border: 0;
            margin: 8px 16px 15px;
            padding: 15px;
            box-sizing: border-box;
            font-size: 14px;
        }

        input[type=number]::-webkit-inner-spin-button,
        input[type=number]::-webkit-outer-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        table {
            width: 85%;
        }

    </style>
    <div class="content-admission-form">
        <div class="admission-form-content-overlay">
            <div class="admission-form-content">
                <div class="admission-form-container-card-header">
                    Fill the form to apply
                </div>

                <div class="admission-form-container-card">

                    <form class="form-horizontal" method="POST" action="">
                        {% csrf_token %}
                        <table>
                            {% for field in application_form %}
                                <tr>
                                    <th>{{ field.label_tag }}</th>
                                    <td>
                                        {{ field.errors }}
                                        {{ field }}
                                        {{ field.help_text }}
                                    </td>
                                </tr>
                            {% endfor %}


                        </table>
                        <br>

                        {{ formset.management_form }}

                        <div id="courseForm_0">
                            <div style="float:left;width:40%;text-align:left;">
                                <span id="completedCourse_0">Completed Course 1</span>
                            </div>

                            <div style="float:right;width:30%;text-align:right;">
                                <span class="delete-course" id="deleteCourse_0" >Delete</span>
                            </div>
                            {% comment %}<div class="col-md-12">
                                <div id="completedCourse_0" class="col-md-10">
                                    <span>Completed Course 1</span>
                                </div>
                                <div class="col-md-2">Delete</div>
                            </div>{% endcomment %}
                            <br><hr>
                            <table id="courseTable">
                                {% for field in formset %}

                                    <th>{{ field.label_tag }}</th>
                                    <td>
                                        {{ field }}

                                    </td>
                                {% endfor %}
                            </table>

                        </div>
                        <br>

                        <div class="input-group-append">
                            <button class="submit-button add-form-row" style="background: #0e6498">Add More Course
                            </button>
                        </div>
                        <br>


                        {% comment %}{% for form in formset %}
                            <div class="row form-row spacer">
                                <div class="input-group">
                                    {{ form.as_p }}
                                    <div class="input-group-append">
                                        <button class="btn btn-success add-form-row">+</button>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
{% endcomment %}

                        <div class="row spacer input-group-append">
                            <button type="submit" class="submit-button">Submit</button>
                        </div>
                    </form>

                </div>


            </div>

        </div>


    </div>


    <script type='text/javascript'>

        var lastId = 0;
        {#init();#}
        function init() {
            $("#deleteCourse_0").hide();

        }

        function updateElementIndex(el, prefix, ndx) {
            var id_regex = new RegExp('(' + prefix + '-\\d+)');
            var replacement = prefix + '-' + ndx;
            if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
            if (el.id) el.id = el.id.replace(id_regex, replacement);
            if (el.name) el.name = el.name.replace(id_regex, replacement);
        }

        function cloneMore(selector, prefix) {
            var newElement = $(selector).clone(true);
            var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
            newElement.find(':input').each(function () {
                var name = '';
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
            });
            total++;
            $('#id_' + prefix + '-TOTAL_FORMS').val(total);
            $(selector).after(newElement);
            var conditionRow = $('.form-row:not(:last)');
            conditionRow.find('.btn.add-form-row')
                .removeClass('btn-success').addClass('btn-danger')
                .removeClass('add-form-row').addClass('remove-form-row')
                .html('<i class="material-icons">remove_circle_outline</i>');
            return false;
        }

        function deleteForm(prefix, btn) {
            var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
            if (total > 1) {
                btn.closest('.form-row').remove();
                var forms = $('.form-row');
                $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
                for (var i = 0, formCount = forms.length; i < formCount; i++) {
                    $(forms.get(i)).find(':input').each(function () {
                        updateElementIndex(this, prefix, i);
                    });
                }
            }
            return false;
        }

        {% comment %}$(document).on('click', '.add-form-row', function (e) {
            e.preventDefault();
            cloneMore('.form-row:last', 'form');
            return false;
        });
        $(document).on('click', '.remove-form-row', function (e) {
            e.preventDefault();
            deleteForm('form', $(this));
            return false;
        });{% endcomment %}

        $(".add-form-row").click(function (e) {
            e.preventDefault();
            addCourseField();


        });

        $(".delete-course").bind('click',function () {
            alert("Hello");

            {#deleteCourseField(this.attr("id"));#}


        });

        function addCourseField() {
            var clonedField = $("#courseForm_" + lastId).clone(true);
            var completedCourse = clonedField.find("#completedCourse_" + lastId);
            var deleteCourse = clonedField.find("#deleteCourse_" + lastId);
            lastId++;
            completedCourse.attr("id", "completedCourse_" + lastId);
            completedCourse.html("Completed Course " + (lastId + 1));
            clonedField.attr("id", "courseForm_" + lastId);
            deleteCourse.attr("id", "deleteCourse_" + lastId);
            deleteCourse.show();
            clonedField.find("input").val("");
            clonedField.insertAfter("#courseForm_" + (lastId - 1));
            clonedField.hide();
            clonedField.slideDown(800);
        }
        
        function deleteCourseField(id) {
            alert("Will Delete"+id);
            
        }


    </script>

{% endblock %}